import "./globals.css";
import { Nunito } from "next/font/google";
import Header from "app/Components/header.js";
import Footer from "app/Components/footer.js";
import {aboutMeData, pages, contactMeLinks} from "@/data/data"

const nunito = Nunito({ subsets: ["latin"] });


export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={nunito.className}>
        <Header pages={pages} aboutMeData={aboutMeData} /> 
        {children}
        <Footer links={contactMeLinks} />
     
      </body>
    </html>
  );
}
